### ISSUE TITLE
remove_run.py unavailable

### ISSUE THREAD

**Issue by corburn** [ssi-dk/bifrost#13]
The remove_run.py script mentioned in the documentation is unavailable in the public repository: https://ssi-dk.github.io/bifrost/#/user_guide?id=removing-a-run-update

The scripts/ directory is in the .gitignore file.

**Comment by martinbaste** [comment]
Fixed in b925e18220604ce58f3c47d9cca4c18c91eda93b

Basically for now I'd recommend to do it using datahandling instead of the scripts. We do have some internal scripts but most are tailored for our internal system unfortunately. We are working on a common CLI tool to do most common tasks
