### ISSUE TITLE
pypi bifrostlib out-of-sync with repository bifrostlib

### ISSUE THREAD

**Issue by corburn** [ssi-dk/bifrost#14]
The pipeline will fail if run with the bifrostlib installed from the PYPI index instead of the repository  because the datahandler.log method was renamed.

https://github.com/ssi-dk/bifrost/blob/ea4ce48b696370c61ad72c5d215a0bc0da0adc36/envs/bifrost_for_install_full.yaml#L36

**Comment by martinbaste** [comment]
Should be fixed now, the right version is 1.2.1
