### ISSUE TITLE
reorder conda environment channels

### ISSUE THREAD

**Issue by corburn** [ssi-dk/bifrost#16]
I suspect the bug cited in the install script is due to the conda channel order.

https://github.com/ssi-dk/bifrost/blob/ea4ce48b696370c61ad72c5d215a0bc0da0adc36/setup/install.sh#L4

https://github.com/ssi-dk/bifrost/blob/ea4ce48b696370c61ad72c5d215a0bc0da0adc36/envs/bifrost_for_install_full.yaml#L3-L6

I encountered a library issue before and it was because bioconda defers non-bio dependencies to the conda-forge channel. They depend on the following channel order:

```yaml
channels:
  - bioconda
  - conda-forge
  - defaults
```

https://bioconda.github.io/user/install.html#set-up-channels

**Comment by martinbaste** [comment]
also fixed in 39908e465db4
