### ISSUE TITLE
chewBBACA component for Bifrost

### ISSUE THREAD

**Issue by ghost** [ssi-dk/bifrost#81]
We need a component that can run chewBBACA and write allele profiles to MongoDB.

**Comment by ghost** [comment]
There is some code in this repo that can JSONify the output from chewBBACA:
https://gitlab.com/bfr_bioinformatics/chewieSnake/-/tree/jsonwriter 
Particularly scripts/json_writer.py

**Comment by sofiehn** [comment]
We'll need the following allele schemes

C. jejuni / C. coli cgMLST v1.0
https://pubmlst.org/bigsdb?db=pubmlst_campylobacter_seqdef&page=downloadAlleles&scheme_id=4&render=1 

Escherichia/Shigella, cgMLST V1+HierCC V1
https://enterobase.warwick.ac.uk/species/ecoli/download_data 

Salmonella, cgMLST V2+HierCC V1
https://enterobase.warwick.ac.uk/species/senterica/download_data

Yersinia, cgMLST V1+HierCC V1
https://enterobase.warwick.ac.uk/species/yersinia/download_data
 
Listeria, cgMLST1748
https://bigsdb.pasteur.fr/cgi-bin/bigsdb/bigsdb.pl?db=pubmlst_listeria_seqdef&page=downloadAlleles&scheme_id=3&render=1


The schemas needs to be run through chewBBACA.py PrepExternalSchema with the training file found under the chewBBACA installation fx /srv/data/tools/anaconda3/envs/shons/pkgs/chewbbaca-2.8.5-pyhdfd78af_0/site-packages/CHEWBBACA/prodigal_training_files to be updated

**Comment by kriskiil** [comment]
Blocked until we find a way to manage biodatabases. (SOFI#108)

**Comment by ghost** [comment]
Migrated to JIRA.
